name: MyShuttle-CICD
on: 
  push:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
       java-version: 1.8
       java-package: jdk
    - name: Build App
      run: mvn -f pom.xml clean package
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
       name: drop
       path: target
 
  deploytoazure:
    runs-on: ubuntu-latest
    needs: build
       
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v1.0.0
      with:
       name: drop 
    - name: Deploy to AzureWebApp
      uses: Azure/webapps-deploy@v1
      with:
        publish-profile: ${{secrets.azure_webapp_publish_profile}}
        app-name: myshuttle12
        package: drop/*.war

